# -*- coding: utf-8 -*-
# skeleton-python-binary -  Command-line tool that generates project templates based on predefined Python project template
# Copyright (C) 2024 - Centre National d'Etudes Spatiales
# SPDX-License-Identifier: Apache-2.0
# Auto-generated by skeleton-python-binary
"""Project metadata."""
import toml
import os

project_root = os.path.dirname(os.path.dirname(__file__))
pyproject_path = os.path.join(project_root, "pyproject.toml")

# Load metadata from pyproject.toml
with open(pyproject_path, "r") as file:
    pyproject_content = toml.load(file)

project_tool = pyproject_content.get("tool", {})
project_metadata = project_tool.get("poetry", {})

__name_soft__ = project_metadata.get("name", "unknown")
__version__ = project_metadata.get("version", "0.0.0")
__title__ = project_metadata.get("name", "unknown")
__description__ = project_metadata.get("description", "")
__url__ = project_metadata.get("homepage", "")
__author__ = project_metadata.get("authors", [{}])[0]
__author_email__ = project_metadata.get("authors", [{}])[0]
__license__ = project_metadata.get("license", "")
__copyright__ = "{{cookiecutter.year}}, {{cookiecutter.institute}} ({{cookiecutter.full_name}} for {{cookiecutter.consortium_name}})"
